name: Release Standalone Binaries

on:
  repository_dispatch:
    types: [prepare-release]

jobs:
  readyRelease:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and tag
        run: |
          git fetch
          git checkout main
          git commit --allow-empty -m "Release ${{ github.event.client_payload.tag }}"
          git tag ${{ github.event.client_payload.tag }}
          git push origin main --follow-tags

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.client_payload.tag }}
          release_name: ${{ github.event.client_payload.tag }}
          body: See CHANGELOG.md in nitrictech/cli for changes
          draft: true
          prerelease: false

      # Signal the releases repostory to prepare a release
      - name: Release Ready
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          repository: nitrictech/cli
          event-type: release-ready
          client-payload: '{"url": "${{ steps.create_release.outputs.upload_url }}", "tag": "${{ github.event.client_payload.tag }}"}'


